version: '3.8'

services:

  mongo:
    image: mongo:jammy
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ScrapyUtxMongo2023!
    volumes:
      - ./data:/data/db
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p ScrapyUtxMongo2023! --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - Scrapy_net

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ScrapyUtxMongo2023!
      - ME_CONFIG_BASICAUTH_PASSWORD=ScrapyUtxMongo2023!
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    networks:
      - Scrapy_net

networks:
  Scrapy_net:
    driver: bridge
